### ISSUE TITLE
Contributor guideline

### ISSUE THREAD

**Issue by phsilva** [kitspace/kicad_footprints#1]
Hi, nice work here.

Would be great if you could add some info about how to contribute repos not yet in this collection.

Found this https://github.com/natsfr/kicad-components and would like to add.

**Comment by kasbah** [comment]
Thanks, I'll try and put something in the readme. I am happy for people just to drop the name of the repository somewhere and I will add it (I just added natsfr/kicad-components). 

If you want to save me a little time the process is pretty similar to any GitHub project and they have loads of help pages e.g. [on forking](https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project), which is the first step. 

The main difference is that we are working with submodules. To add a submodule to your fork, you have to clone it locally and:

```
git submodule add https://github.com/natsfr/kicad-components natsfr/kicad-components
git commit -m "Add natsfr/kicad-components"
git push
``` 

The naming scheme we are using for the folders is `<user-name>/<repository>` like the GitHub URLs. 

And then [open a pull request](https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request) to add this to the main repo. There are no other guidlines really, if it contains KiCAD footprints it will be accepted.
