### ISSUE TITLE
KiCAD footprint repositories that have not been added

### ISSUE THREAD

**Issue by robkam** [kitspace/kicad_footprints#14]
https://github.com/4ms/4ms-kicad-lib/tree/master/lib-footprints
https://github.com/4ms/4ms-kicad-lib/tree/master/4ms-footprints.pretty
https://github.com/tristan-smith/HA_KicadLibraries
https://github.com/russellmcc/russell_kicad/tree/master/russell.pretty
https://github.com/russellmcc/eurorack_kicad/tree/master/eurorack.pretty
https://github.com/recursinging/kxmx/tree/master/kxmx_erack/kicad/kicad/libraries/krachmacher.pretty
https://github.com/nebs/eurocad/tree/master/Eurocad.pretty
https://github.com/peekpt/kicad_smisioto/tree/master/modules/walter

**Comment by kasbah** [comment]
Thanks, added!
