### ISSUE TITLE
Include a config file to exclude libraries

### ISSUE THREAD

**Issue by randrej** [kitspace/kicad_footprints#18]
It'd be convenient if we could ignore any number of these submodules. A simple `ignore_modules` file would suffice, one ignored submodule name per newline. This way I could ignore some repos, for example the official one (because I already have it in my distro).

**Comment by kasbah** [comment]
Not a bad idea. Are you up for implementing it?

**Comment by randrej** [comment]
Yeah, sure, I'll do it when I have some time, probably some weekend.

**Comment by kasbah** [comment]
Implemented with #21 !
