### ISSUE TITLE
Does this also work with KiCad 5.99 nightly (de-facto version 6.0)?

### ISSUE THREAD

**Issue by exislow** [kitspace/kicad_footprints#20]
I have installed kiCad nightly 5.99, which will be the upcomming version 6. But apparently this method is not compatible with 5.99. Is there a fix for that?

**Comment by kasbah** [comment]
I think it should. What do you mean by "this method"? Writing to the fp-lib-table? On my install the nightly fp-lib-table is in `~/.config/kicadnightly/5.99/fp-lib-table` so you'd have to use replace that in the proposed commands in the readme. If that doesn't solve your issue it would help if you were a little more descriptive:

- What are you trying?
- What are you expecting to happen?
- What is actually happening?
- What platform are you on?
